2025-04-18 17:30:43,477 INFO    Thread-8  :3680772 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-04-18 17:30:43,477 INFO    Thread-8  :3680772 [wandb_setup.py:_flush():68] Configure stats pid to 3680772
2025-04-18 17:30:43,477 INFO    Thread-8  :3680772 [wandb_setup.py:_flush():68] Loading settings from /speech/shoutrik/.config/wandb/settings
2025-04-18 17:30:43,477 INFO    Thread-8  :3680772 [wandb_setup.py:_flush():68] Loading settings from /speech/shoutrik/torch_exp/my_own/wandb/settings
2025-04-18 17:30:43,477 INFO    Thread-8  :3680772 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-04-18 17:30:43,478 INFO    Thread-8  :3680772 [wandb_init.py:_log_setup():528] Logging user logs to /speech/shoutrik/torch_exp/my_own/wandb/run-20250418_173043-0vfxegcp/logs/debug.log
2025-04-18 17:30:43,478 INFO    Thread-8  :3680772 [wandb_init.py:_log_setup():529] Logging internal logs to /speech/shoutrik/torch_exp/my_own/wandb/run-20250418_173043-0vfxegcp/logs/debug-internal.log
2025-04-18 17:30:43,479 INFO    Thread-8  :3680772 [wandb_init.py:init():644] calling init triggers
2025-04-18 17:30:43,479 INFO    Thread-8  :3680772 [wandb_init.py:init():650] wandb.init called with sweep_config: {'batch_norm': True, 'batch_size': 256, 'conv_activation': 'ReLU', 'data_aug': True, 'dense_activation': 'ReLU', 'dropout_prob': 0.5, 'epochs': 15, 'filter_size': [5, 5, 5, 5, 5], 'hidden_size': 1024, 'learning_rate': 0.001, 'n_filters': [512, 256, 128, 64, 32], 'num_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.005, 'weight_init': 'default'}
config: {}
2025-04-18 17:30:43,479 INFO    Thread-8  :3680772 [wandb_init.py:init():680] starting backend
2025-04-18 17:30:43,479 INFO    Thread-8  :3680772 [wandb_init.py:init():684] sending inform_init request
2025-04-18 17:30:43,494 INFO    Thread-8  :3680772 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-18 17:30:43,495 INFO    Thread-8  :3680772 [wandb_init.py:init():697] backend started and connected
2025-04-18 17:30:43,497 INFO    Thread-8  :3680772 [wandb_run.py:_config_callback():1279] config_cb None None {'batch_norm': True, 'batch_size': 256, 'conv_activation': 'ReLU', 'data_aug': True, 'dense_activation': 'ReLU', 'dropout_prob': 0.5, 'epochs': 15, 'filter_size': [5, 5, 5, 5, 5], 'hidden_size': 1024, 'learning_rate': 0.001, 'n_filters': [512, 256, 128, 64, 32], 'num_layers': 5, 'optimizer': 'adam', 'weight_decay': 0.005, 'weight_init': 'default'}
2025-04-18 17:30:43,502 INFO    Thread-8  :3680772 [wandb_init.py:init():790] updated telemetry
2025-04-18 17:30:43,504 INFO    Thread-8  :3680772 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-04-18 17:30:44,299 ERROR   Thread-8  :3680772 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 825, in init
    result = run_init_handle.wait(
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "/speech/shoutrik/espnet/tools/anaconda/envs/espnet/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
Exception
2025-04-18 17:30:44,329 WARNING MsgRouterThr:3680772 [router.py:message_loop():75] message_loop has been closed
